spring: # 주의할 점은 내용작성시 들여쓰기 내어쓰기시 공백개수를 반드시 꼭 지켜야 한다.
  application:
    name: PerfumeArena_S
 
  profiles: #실행환경(dev(개발),test(테스트),local(로컬),prod(운영))
    active: local 
    
  mvc:
    view: #뷰 리졸버. view 경로 및 확장자 지정하기. JSP를 뷰로 사용한다.  
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource-semiorauser2: #DB 접속이 1개만 있을 경우
    driver-class-name: oracle.jdbc.OracleDriver
    jdbcUrl: jdbc:oracle:thin:@127.0.0.1:1521:xe # 2개의 datasource 를 설정하려면 기본 스프링 부트 datasource 설정과는 다르게 url 로 되어있던 부분을 jdbcUrl 로 변경해야 한다. JavaConfig 를 통해 사용자가 직접 지정하여 데이터 소스를 구성할 경우 url 이 아닌 jdbcUrl 을 사용하기 때문이다.
    username: semi_orauser2
    password: seven
    type: com.zaxxer.hikari.HikariDataSource
    hikari: 
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000    

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect      # Spring Boot 3.2.1 버전 이후 부터는 JPA Provider가 적절한 Dialect 를 찾아내게 해주므로, 즉 설정을 명시하지 않아도 Oracle을 자동 인식해주므로 이를 명시적으로 지정하게 되면 오류가 발생하게 된다.  

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        '[show_sql]': true         
        '[format_sql]': true
        '[use_sql_comments]': true

    open-in-view: false
          
  data: #=== (몽고DB) === 
    mongodb:
      uri: mongodb://devuser:qwer1234$@127.0.0.1:27017/mydb
      
  messages: #메시지(파일이 여러개일 경우 ,로 구분)
    basename: messages.validation
    encoding: UTF-8

  devtools: #View reload
    livereload:
      enabled: true

    restart: #컨트롤러, 모델단이 바뀌었을 때 프로젝트 재시작(reload) 설정 (정확히는 classpath에 있는 모든 파일)
      enabled: true #재시작(reload) 함

  servlet:
    multipart:
      max-file-size: 10MB     # 파일 업로드 용량제한 설정하기. 파일 업로드 용량을 설정하지 않으면 기본값은 1048576 bytes (1MB)으로 된다.
      max-request-size: 12MB  # 파일 및 파일을 제외한 input 태그값 업로드 용량제한 설정하기. 업로드 용량을 설정하지 않으면 기본값은 1048576 bytes (1MB)으로 된다.


mybatis: #mybatis 설정
 #type-aliases-package: com.spring.app.**.domain 
 #mapper-locations: com/spring/app/**/mapper/*.xml   #src/main/java 아래 패키지속에 매퍼파일을 만드는 경우 
  mapper-locations: mybatis/mapper/**/*.xml          #src/main/resources 아래 폴더속에 매퍼파일을 만드는 경우
logging: #로그 지정
  level:
    #root: error
    '[com.spring.board]': debug 
    #com.zaxxer.hikari.HikariConfig: DEBUG
    #com.zaxxer.hikari: TRACE 

server:
  tomcat:
    max-part-count: 30 
  port: 9092
  servlet:
    context-path: /PerfumeArena  # Spring Framework 에서는 WAS 톰캣서버를 더블클릭하여 context Path 를 수정하였으나 Spring Boot 에서는 여기에서 한다. context-path: 를 주석처리하면 context Path 가 없는 것이다.
                                    # context-path 를 /myspring 으로 주었으므로 Boot Dashboard 에 가서 myspring 에 마우스 우측클릭 Show Properties 에 클릭하여 General 에서 Path: 란에 myspring 을 입력해준다.  
    encoding:
      charset: UTF-8
      enabled: true #http 인코딩 지원을 활성화할지 여부
      force: true #post 방식으로 전송했을때 한글데이터가 안깨지도록 함. # Spring Framework 에서는 web.xml 파일에서 filter 태그를 등록시켜 주었음.

coolsms:
  api-key: NCSE8ZY9FPICT0IH
  api-secret: FLQ9ADWJCMPVHGYINE6NL7DOEDYBLD4P
  from: 01049221986